services:
  sandbox:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    environment:
      - GIN_MODE=release

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      sh -c "ollama serve & sleep 2 && ollama pull llama3 && wait"

volumes:
  ollama_data: